### ISSUE TITLE
org-pivotal-api--store-story: Symbol’s value as variable is void: org-file-properties

### ISSUE THREAD

**Issue by rezmuh** [org-pivotal/org-pivotal#6]
Hi, I just came across this project and wanted to try it out. I am currently having an issue with pushing and pulling stories.

In an empty org file, I could do `M-x org-pivotal-install-project-metadata` and I got to choose the projects associated with my API key. Then, I have the additional properties creatd by org-pivotal.

I then tested to create a new story. However, when I tried to push this to PT with `M-x org-pivotal-push-story`, I got the following error:

```org-pivotal-api--store-story: Symbol’s value as variable is void: org-file-properties```

If I try to pull the stories with `M-x org-pivotal-pull-stories`, I got the same error.

my config only has the following:

(setq org-pivotal-api-token "xxx")
(add-hook 'org-mode-hook 'org-pivotal-mode)

It would be great if I could use this seamlessly :)

![Screen Shot 2019-12-16 at 12 24 50](https://user-images.githubusercontent.com/1204244/70881574-9713cc00-1fff-11ea-9f89-ee7fc705a9af.png)

**Comment by qhuyduong** [comment]
Pushing new story to pivotal is still being built :smile: Meanwhile only fetching and pushing existing stories are supported.

**Comment by sandinmyjoints** [comment]
Should be fixed by https://github.com/org-pivotal/org-pivotal/issues/6
